---
# tasks file for template

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

#- name: Restart server
#  shell: sleep 2 && shutdown -r now
#  async: 1
#  poll: 0
#  ignore_errors: true
#
#- name: Rebotando equipo
#  shell: /sbin/shutdown -r now && sleep 1
