---
# tasks file for template

- name: Install external EPEL repository
  yum_repository:
    name: epel
    state: present
    description: EPEL YUM repo
    baseurl: "https://dl.fedoraproject.org/pub/epel/$releasever/$basearch/"
    gpgkey: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    gpgcheck: "yes"

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

#- name: Restart server
#  shell: sleep 2 && shutdown -r now
#  async: 1
#  poll: 0
#  ignore_errors: true
#
#- name: Rebotando equipo
#  shell: /sbin/shutdown -r now && sleep 1
