---
# tasks file for template

#- name: Install epel-release
#  yum:
#    name: epel-release
#    state: latest
#
#- name: Upgrade all packages
#  yum:
#    name: '*'
#    state: latest



- name: Change IP
   lineinfile: 
     dest: /etc/sysconfig/network-scripts/ifcfg-eth0
     regexp: '^(.*)IPADDR="172.26.0.21"(.*)$' 
     line: 'IPADDR="{{ ip_equipo }}"'
     backrefs: yes


#- name: Restart server
#  shell: sleep 2 && shutdown -r now
#  async: 1
#  poll: 0
#  ignore_errors: true
#
#- name: Rebotando equipo
#  shell: /sbin/shutdown -r now && sleep 1
