---
# tasks file for template

#- name: Upgrade all packages
#  yum:
#    name: '*'
#    state: latest

- name: Tunning SSH DNS
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^#UseDNS yes'
    replace: 'UseDNS no'

- name: Tunning SSH GSSAPIAuthentication
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^#GSSAPIAuthentication yes'
    replace: 'GSSAPIAuthentication no'

- name: Restart service sshd, in all cases
  service:
    name: sshd
    state: restarted

- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: Change IP
  replace: 
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: '^IPADDR="172.26.0.21"'
    replace: 'IPADDR="{{ ip_equipo }}"'

- name: Change Hostname
  replace: 
    path: /etc/hostname
    regexp: '^template'
    replace: '{{ hostname_equipo  }}'

- name: Intalacion de paquetes
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - htop

#- name: Restart server
#  shell: sleep 2 && shutdown -r now
#  async: 1
#  poll: 0
#  ignore_errors: true
#
#- name: Rebotando equipo
#  shell: /sbin/shutdown -r now && sleep 1
